spring:
  application:
    name: order-service

  profiles:
    default: local

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      label: develop
      fail-fast: false

trusta:
  security:
    trust-gateway-headers: true
