spring:
  application:
    name: order-service

  main:
    # common JpaConfig 의 auditorAware 빈을 본 서비스 JpaAuditingConfig 가 override
    allow-bean-definition-overriding: true

  profiles:
    default: local

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      label: develop
      fail-fast: false

trusta:
  security:
    trust-gateway-headers: true
